{"name": "test_case02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 20\n  -10\n  +20", "trace": "self = <Allure_report1.test_file01.Test_Suite01 object at 0x03B38830>\n\n    def test_case02(self):\n        print(\"Hello, Am from test case 02\")\n        i = 10\n>       assert i == 20\nE       assert 10 == 20\nE         -10\nE         +20\n\ntest_file01.py:26: AssertionError"}, "start": 1582514934260, "stop": 1582514934260, "uuid": "63e9eedd-6e26-4828-9a24-a5963a627395", "historyId": "fae923919d3d5f28489b2cff89fab9ab", "testCaseId": "1033e4a43a4fe4123d508aafdfc8fab3", "fullName": "test_file01.Test_Suite01#test_case02", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_file01"}, {"name": "subSuite", "value": "Test_Suite01"}, {"name": "host", "value": "com2"}, {"name": "thread", "value": "2120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file01"}]}