{"name": "test_case02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 20", "trace": "self = <Allure_report1.test_file01.Test_Suite01 object at 0x0376A710>\n\n    def test_case02(self):\n        print(\"Hello, Am from test case 02\")\n        i=10\n>       assert i==20\nE       assert 10 == 20\n\ntest_file01.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "aca047d7-2f3e-4664-ae5d-9640ec552ce4-attachment.txt", "type": "text/plain"}], "start": 1577335068628, "stop": 1577335068628, "uuid": "929e0028-9321-4a38-af77-54717ad7e6ce", "historyId": "fae923919d3d5f28489b2cff89fab9ab", "testCaseId": "1033e4a43a4fe4123d508aafdfc8fab3", "fullName": "test_file01.Test_Suite01#test_case02", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_file01"}, {"name": "subSuite", "value": "Test_Suite01"}, {"name": "host", "value": "com2"}, {"name": "thread", "value": "5244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file01"}]}